### ISSUE TITLE
Cannot override inherited member Pull()

### ISSUE THREAD

**Issue by romeroej2** [BosslandGmbH/SenseibuddyBugs#13]
Cannot override Task Pull since its not marked properly?

CombatRoutineBase -> public Task Pull(object preferredTarget);

Think this was already reported by Zzi and fixed in the next version.

**Comment by zzi-zzi-zzi** [comment]
Yes

![ss 2016-07-24 at 06 45 25](https://cloud.githubusercontent.com/assets/18638210/17087036/d43becd2-51ce-11e6-96f2-13a2ad83afb4.jpg)
