### ISSUE TITLE
Crash during navigation

### ISSUE THREAD

**Issue by zzi-zzi-zzi** [BosslandGmbH/SenseibuddyBugs#14]
Attached is log & dmp

[BNS 8844 2016-07-28-23.19.00.log.txt](https://github.com/BosslandGmbH/SenseibuddyBugs/files/389593/BNS.8844.2016-07-28-23.19.00.log.txt)

(not really a text file but couldn't get it to upload any other way)
[BnSCrashReport.xml.txt](https://github.com/BosslandGmbH/SenseibuddyBugs/files/389600/BnSCrashReport.xml.txt)

**Comment by ApocDev** [comment]
Fixed by disabling path hop debugging.
