### ISSUE TITLE
UI Missing Functionality to enable Teleportation. (Windstride)

### ISSUE THREAD

**Issue by zzi-zzi-zzi** [BosslandGmbH/SenseibuddyBugs#9]
Currently not able to use teleportation. via UI manipulation or otherwise. This is required as some zones can only be accessed via teleportation. 

There is at least one quest that requires teleportation.

The UI Node UCUstomUIMiniMap does not show any children which I believe is what holds the Teleport buttons so this cannot be done via UI manipulation. Ideally there is another way to do this other than UI manipulation. 

**Exact UI Node location:** `MapWindowPanel.MapWindow_MapHolder.MapWindow_Minimap`

**Comment by ApocDev** [comment]
The UI was not missing the functionality. It has been wrapped using the Windstride tag.
